Repository UPE-FIU/Turtle, pull requests merged in 2019-08, with the labels that each got.

#1 fixed google sheet issue, updated errors in email templates
  .gitignore
  src/controllers/application.js
  src/models/applicant.js
  src/services/application.js
  src/services/google/sheets.js
  src/services/mail.js
  src/templates/forgot_password.handlebars
  src/templates/reset_password.handlebars
  yarn.lock
Labels: enhancement

#3 changed subject lines for forgot pas, reset pass, verification email,…
  src/services/mail.js
Labels: enhancement

#4 Removed Blind Carbon Copy email from mail.js
  src/services/mail.js
Labels: enhancement

#5 Fixed error where emails weren't being lower cased when comparing for…
  src/controllers/announcement.js
  src/controllers/application.js
Labels: bug

#13 Fixed token validation issue
  src/services/application.js
Labels: bug

#14 deploying changes
  src/services/application.js
Labels: update

#19 Feature/verification fixes
  src/controllers/application.js
  src/templates/verify_email.handlebars
Labels: enhancement

#27 added database authentication
  src/db/index.js
Labels: enhancement

#34 updated reminder email contents
  .DS_Store
  src/services/mail.js
  src/templates/acceptance.handlebars
  src/templates/acceptance_confirmation_reminder.handlebars
  src/templates/accepted_confirmation.handlebars
  src/templates/account_confirmation.handlebars
  src/templates/application_confirmation.handlebars
  src/templates/application_reminder.handlebars
  src/templates/forgot_password.handlebars
  src/templates/reset_password.handlebars
  src/templates/verify_email.handlebars
Labels: enhancement
